spring:
 cloud:
   gateway:
     routes:
       - id: order-service
         uri: lb://ORDER_SERVICE
         predicates:
           - Path=/order/**
         filters:
           - AuthenticationFilter


       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/