server:
  port: 9898

spring:
  application:
    name: auth-service
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:user-db
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
