spring:
 cloud:
   gateway:
     routes:
       - id: order-service
         uri: lb://ORDER-SERVICE
         predicates:
           - Path=/order/**

       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**

 application:
   name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/